name: "Changelog Tool"
author: "Rodrigo Machado"
description: "Manipulate changelog files that follows keepachangelog.com format."

branding:
  icon: "file-text"
  color: "green"

inputs:
  args:
    description: Pass arguments to changelog command
    required: true

outputs:
  output:
    description: The output from the changelog command

runs:
  using: "docker"
  image: Dockerfile
  args:
    - ${{ inputs.args }}
