on: [push]

jobs:
  init:
    runs-on: ubuntu-latest
    name: init
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Create dummy changelog file
        run: touch CHANGELOG.md
      - name: Run changelog init
        uses: ./
        id: init
        with:
          args: init --output CHANGELOG.md --compare-url https://example.com/abcdef...HEAD
      - name: Run changelog release
        uses: ./
        id: release
        with:
          args: release --output CHANGELOG.md 1.0.0
